### ISSUE TITLE
crashed in windows server 2019

### ISSUE THREAD

**Issue by jsd1t** [FIFARenderZ/EPYC-Rome-Overclock#3]
The newest version 1.0.1 just crashed in windows server 2019, while 1.0.0 is ok.
When I try to run the v1.0.1 program, nothing happen after double clicking. But i can definitely find the RomeOverclock process in task manager, and quickly the process disappeared.

And there are some trouble about the CPU Voltage turning, I wanna know what things will be changed after applying Voltage setting? Someone told that applying Voltage may damage CPU even with a normal Voltage such as 1.05V.
Thanks.

**Comment by FIFARenderZ** [comment]
Hmm, that's definitely interesting. I'm kinda short on time right now, so you'll just have to use the 1.0.0 version for now.

As for the voltage: it doesn't really do anything, so you're fine avoiding it

**Comment by rantonxl** [comment]
Have same issue. Version 1.0.1 not starting and 1.0.0 works fine. Windows Server 2019 Std

**Comment by valp124** [comment]
Same issue here. But I think I might know why it's crashing. Found this in the Windows event viewer:
```
Exception Info: System.IO.FileNotFoundException
   at RomeOverclock.SettingManager+Settings.DeserializeFromJson(System.String)
   at RomeOverclock.SettingManager..ctor(System.String)
   at RomeOverclock.MainForm..ctor()
   at RomeOverclock.Program.Main()
```
Looking at the code, it seems that the file `settings.json` has to be present:

https://github.com/FIFARenderZ/EPYC-Rome-Overclock/blob/eb48523e4e213a552d8888668b7c9e778115b80d/RomeOverclock/MainForm.cs#L14

https://github.com/FIFARenderZ/EPYC-Rome-Overclock/blob/eb48523e4e213a552d8888668b7c9e778115b80d/RomeOverclock/MainForm.cs#L106

https://github.com/FIFARenderZ/EPYC-Rome-Overclock/blob/eb48523e4e213a552d8888668b7c9e778115b80d/RomeOverclock/smu/SettingManager.cs#L211

Having said that -- I created `settings.json` file in the directory where I run the exe from and still got the same error, which I have hard time explaining...
